name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: periuz
          outputs: |
            ./dist/github-contribution-grid-snake.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate GitHub contribution snake"
          add: "dist/github-contribution-grid-snake.svg"
